name: terraform-ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  ci:
    uses: SPHTech-Platform/reusable-workflows/.github/workflows/terraform.yaml@main
    with:
      upload_sarif: true

